# Generated by Django 3.1.6 on 2021-02-09 14:33

from django.db import migrations

def create_data(apps, schema_editor):
    Customer = apps.get_model('usercase', 'Customer')
    Customer(first_name="Customer 001", email="customer001@email.com", description= "Customer 001 description").save()
class Migration(migrations.Migration):

    dependencies = [
        ('usercase', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_data),
    ]
