# Generated by Django 3.1.5 on 2021-01-19 09:21

from django.db import migrations
def create_data(apps, schema_editor):
    Customer = apps.get_model('usercase', 'Customer')
    Customer(first_name="Customer 001", email="customer001@email.com", description= "Customer 001 description",tags="events").save()


class Migration(migrations.Migration):

    dependencies = [
        ('usercase', '0002_customer_getstar'),
    ]

    operations = [
    migrations.RunPython(create_data),
    ]
