# Generated by Django 3.1.5 on 2021-02-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercase', '0003_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.TextField(default='event'),
            preserve_default=False,
        ),
    ]
