# Generated by Django 3.1.7 on 2021-03-31 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usercase', '0004_auto_20210331_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovely',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
