# Generated by Django 3.1.7 on 2021-04-15 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usercase', '0006_auto_20210331_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag1', models.CharField(default='', max_length=100)),
                ('tag2', models.CharField(default='', max_length=100)),
                ('category1', models.CharField(default='', max_length=100)),
                ('category2', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
